# -*- coding: utf-8 -*-
"""Covid-19 Risk.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h01rM3f-GXFM71ZyV3woqZrtasm5v5r2
"""

# Task: Estimating the risk of death from coronavirus.

age = input("Are you a cigarette addict older than 75 years old?  ").lower()
chronic = input("Do you have a severe chronic desease?  ").lower()
immune = input("İs your immune system too weak  ").lower()



if age == "yes" or chronic == "yes" or immune == "yes":
  print("You are in risky group")
else:
  print("You are not in risky group")